
services:
    mongo:
        image: mongo:6
        container_name: card_sorter_mongodb_dev
        
        ports:
            - "27017:27017"
        environment:
          MONGO_INITDB_ROOT_USERNAME: "rest_api"
          MONGO_INITDB_ROOT_PASSWORD: "password"
          MONGO_INITDB_DATABASE: "card_sorter"
          
        volumes:
            - ./mongodata:/data/db

    mongo-seed:
      build: ./mongoseed
      depends_on:
        - mongo

    mongo-express:
      image: mongo-express:latest
      container_name: card_sorter_mongo_express_dev
      
      ports:
        - "8081:8081"
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: "rest_api"
        ME_CONFIG_MONGODB_ADMINPASSWORD: "password"
        ME_CONFIG_MONGODB_SERVER: "mongo"
        ME_CONFIG_BASICAUTH_USERNAME: rest_api
        ME_CONFIG_BASICAUTH_PASSWORD: password
      depends_on:
        - mongo
